db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci
db.user=root
db.password=root